services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - /opt/users/${CONFIG}/mysql:/var/lib/mysql
      - /opt/konfiguracje/mysql/my.cnf-02gb:/etc/my.cnf
      - /backups/${CONFIG}/mysql:/dumps
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${CONFIG}"
      MYSQL_USER: "${CONFIG}"
      MYSQL_PASSWORD: "${CONFIG}12345"
      LANG: "pl_PL.UTF-8"
      TZ: "Europe/Warsaw"
    networks:
      default:
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "2"
          memory: "2G"

  php-fpm:
    image: rhsmart/moodle-php-fpm:${PHP_VERSION}
    volumes:
      - /opt/konfiguracje/php-fpm/fpm-www.conf-02gb:/usr/local/etc/php-fpm.d/www.conf
      - /opt/users/${CONFIG}/www:/var/www
      - /opt/users/${CONFIG}/moodledata:/var/moodledata
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 134217728         
    networks:
      default:
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '2'
          memory: "2G"

  nginx:
    image: rhsmart/moodle-fpm-nginx:latest
    volumes:
      - /opt/users/${CONFIG}/www:/var/www
      - /opt/users/${CONFIG}/moodledata:/var/moodledata
    networks:
      default:
      traefik-external:          
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '2'
          memory: "512m"
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.lbswarm=true"
        
        - "traefik.http.routers.${CONFIG}.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${CONFIG}.entrypoints=web"
        - "traefik.http.routers.${CONFIG}.middlewares=redirectscheme@file"
        
        - "traefik.http.routers.${CONFIG}-tls.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${CONFIG}-tls.entrypoints=websecure"
        - "traefik.http.routers.${CONFIG}-tls.service=${CONFIG}-tls"
        - "traefik.http.routers.${CONFIG}-tls.tls=true"
        - "traefik.http.routers.${CONFIG}-tls.middlewares=${CONFIG}-tls"
        - "traefik.http.routers.${CONFIG}-tls.tls.certresolver=myresolver"
        - "traefik.http.services.${CONFIG}-tls.loadbalancer.server.port=80"
        - "traefik.http.middlewares.${CONFIG}-tls.chain.middlewares=tlsHeaders@file,http-compress@file,cors@file"

networks:
  default:
  traefik-external:
    external: true
    
